data_ingestion:
  artifacts: artifacts/data
  filename: Dataset.csv
  db_name: projects 
  table_name: phishing_url_dataset

data_validation:
  artifacts: artifacts/validation
  validation_status_file: validation_status.json

data_transformation:
  artifacts: artifacts/transformation
  complete_transformed_filename: transformed_data.csv
  training_data_filename: train_data.csv
  testing_data_filename: test_data.csv
  scaler_filename: datascaler.pkl 