version: "3.9"
services:
  app:
    build: 
      context: . 
      dockerfile: Dockerfile.app 
    environment:
      - API_URL=http://api:7860/predict
    ports:
      - "8080:7860"
    depends_on:
      - api
  api:
    build: 
      context: . 
      dockerfile: Dockerfile.server 
    ports:
      - "8000:7860" 