INP_COLS: 
  url: object 
  url_len: int64  
  dom: object 
  dom_len: int64  
  is_ip: int64  
  tld: object 
  tld_len: int64  
  subdom_cnt: int64  
  letter_cnt: int64  
  digit_cnt: int64  
  special_cnt: int64  
  eq_cnt: int64  
  qm_cnt: int64  
  amp_cnt: int64  
  dot_cnt: int64  
  dash_cnt: int64  
  under_cnt: int64  
  letter_ratio: float64
  digit_ratio: float64
  spec_ratio: float64
  is_https: int64  
  slash_cnt: int64  
  entropy: float64
  path_len: int64  
  query_len: int64  
TARGET_COL: 
  label: int64  